# Generated by Django 3.2.9 on 2021-12-02 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20211202_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributor',
            name='permission',
            field=models.CharField(choices=[('overseer', 'Overseer'), ('contributor', 'Contributor')], default=None, max_length=128),
        ),
    ]
