# Generated by Django 3.2.9 on 2021-12-09 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_contributor_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='project',
            field=models.CharField(default=None, max_length=128),
        ),
    ]
