# Generated by Django 3.2.9 on 2021-12-09 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_comment_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='desc',
            new_name='description',
        ),
    ]
